language: node_js
node_js:
  - '8'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  - cd configurator/
  - yarn dist
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  skip_cleanup: true
  on:
    tags: true